language: node_js

node_js:
  - 'stable'
  - '8'
  - '6'

before_install:
- npm install -g typescript

script:
- ng build

cache: 
  directories:
    - node_modules

deploy:
  provider: firebase
  token:
    secure: bKFz5ybXC1U3NwAwsrQVMNPndZhvmrLBZ1yGjPQ7m/dHXZeYui6e/xAoX6/jawZ2Q1biGox+svfFcvvkqodkOBMw5zLOD1XHLfID0Wash4VI4LueUNwb/POUlumegON7ZmczWY9mVhyuSvgz1n5Voox4xq6NZ5yQIQc4rIfouGGD6Idtspp9rpzzWxkVXtIMslIIlgbSpojxSf6WjZzW621EzMG01UkO3mOF5ZgfHtKXUX35XQK0vMDjfokCjzF6fvRN6p7w5Ih6M76mxNvLRrMT7rJrZYUgp35hLYv94foUnsNAfCMN1A6tCGkmlNQk3Cwh04UL24AIHdR+7MOdnIBqTNO0SLF36C45XZZdTXv1C4v5LNit4Xan/E9Ipw73LA0lzRRcMeT45VvRJ7ZdpQbvMavYSMFr/WxOfpN1XDE2O/noMKuLO9SDrw7qIh8bu176t72H0ksd7NVmJgHQnNbRvCRL9PLMmO1JRbzFwBq0O6t+EQNhj5wTujJw1+fu3IO6ApQFhzJWGA/+BR6TlvfcrWH8o/GVf5nXqtv4bgG5Qb7j0ur4gFPMBBpAvio3HLq5pLRMMet1Sv9QVSKNxDC3fpRg69ayEX7hWP9p3DOxsUwaLxTx7hqSUFqdbGMBBppmOxJgGcqaSgALfvAbslqlmNal9hEbXpUIEIw7LJo=